const {
    REACT_APP_BASE_URL_CONTROL_REST,
    REACT_APP_BASE_URL_DATA_REST, 
    REACT_APP_IS_MOCKUP
} = process.env;

export const BASE_URL_CONTROL_REST = REACT_APP_BASE_URL_CONTROL_REST;
export const BASE_URL_DATA_REST = REACT_APP_BASE_URL_DATA_REST;
export const IS_MOCKUP = REACT_APP_IS_MOCKUP === "true";
